name: Deploy Lambda to S3

on:
  push:
    branches:
      - main # Run this workflow on every push to the main branch
env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Create a virtual environment and activate it
    - name: Create virtual environment
      run: |
        python -m venv lambda-env
        source lambda-env/bin/activate

    # Install dependencies into the virtual environment
    - name: Install dependencies
      run: |
        source lambda-env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Package dependencies and the Lambda function into a ZIP file
    - name: Create Zip file with dependencies
      run: |
        source lambda-env/bin/activate
        cp -r lambda-env/lib/python3.9/site-packages/. .
        zip -r image_time_analysis.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::713984691710:role/github_action_role
        aws-region: ${{ env.AWS_REGION }}
          
    # Upload the zip file to the S3 bucket
    - name: Upload to S3
      run: aws s3 cp image_time_analysis.zip s3://mc-portfolio-s3-4-lambdas/img_processing/image_time_analysis.zip
